version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888" # 左邊是主機端口，右邊是容器內端口ports:
    volumes:
      - .:/app # 開發時同步程式碼變更
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://money_note:password@db:5432/money_note_db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: money_note
      POSTGRES_PASSWORD: password
      POSTGRES_DB: money_note_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
